### PR TITLE
justin header and footer

### PR DESCRIPTION
**Pull request by skgtjt1**
I added header and footer content with a little CSS styling

### CODE REVIEW

**Comment by Adlam4002** [comment]
Are you guys managing your own merge requests? Or do I have to do it as the original host?

**Comment by skgtjt1** [comment]
> Are you guys managing your own merge requests? Or do I have to do it as the original host?

I don't know.... It said I could automatically merge it earlier but now I can't.

**Comment by Adlam4002** [comment]
it says conflicts need resolving 
maybe try resolving them, well see if you can I mean  as a contributor

**Comment by skgtjt1** [comment]
I'll wait to see how based on the demo, the symbols mean nothing to me atm XD

**Comment by Adlam4002** [comment]
fair enough

**Pull request merged**
